spring.application.name=albeniz
# Management
management.endpoints.web.base-path=/tooling

# Server
server.error.whitelabel.enabled=false
server.servlet.context-path=/albeniz

# Application
application.api.maxCollection: 11
application.api.ascending: false